export const RECEIVE_PROPOSALS = 'RECEIVE_PROPOSALS';
export const FETCHING_PROPOSALS = 'FETCHING_PROPOSALS';
export const RECEIVE_PROPOSAL = 'RECEIVE_PROPOSAL';
export const FETCHING_PROPOSAL = 'FETCHING_PROPOSAL';
export const ADDING_PREMISE = 'ADDING_PREMISE';
export const FETCHING_PREMISE_NODES = 'FETCHING_PREMISE_NODES';
export const RECEIVE_PREMISE_NODES = 'RECEIVE_PREMISE_NODES';
export const ADDED_PREMISE = 'ADDED_PREMISE';
