export const RECEIVE_PROPOSALS = 'RECEIVE_PROPOSALS';
export const FETCHING_PROPOSALS = 'FETCHING_PROPOSALS';
export const RECEIVE_PROPOSAL = 'RECEIVE_PROPOSAL';
export const FETCHING_PROPOSAL = 'FETCHING_PROPOSAL';
